### PR TITLE
added colorbar assets for testing

### PR DESCRIPTION
**Pull request by bollu**
please merge this before merging the [colorbar pull request](https://github.com/vispy/vispy/pull/979) in ```vispy/vispy```

### CODE REVIEW

**Comment by campagnola** [comment]
Would you mind moving these to `/visuals/colorbar/*` ? I know that's not how we've done it in the past, but might as well start here :)

**Comment by bollu** [comment]
@campagnola: sure :)

**Comment by bollu** [comment]
@campagnola I forced a push (non fast-forward), but the old commit is still in the UI. Did I mess up in some way?

**Comment by bollu** [comment]
@campagnola done!

**Comment by campagnola** [comment]
Make sure you tag the commit (use `git push --tags`) and update image_tester.py:
https://github.com/vispy/vispy/blob/master/vispy/testing/image_tester.py#L361

**Comment by bollu** [comment]
@campagnola what should I tag this as? anything? or is there a naming convention?

**Comment by campagnola** [comment]
In the link above, the name is `test-data-1`, so you can use `test-data-2`.
..actually, I think I need to tag it since I just did the merge :)

**Comment by bollu** [comment]
@campagnola ah, thanks. And as for the merge, if I push onto the branch, I think you can re-merge?

**Comment by bollu** [comment]
nope, guess that doesn't work

**Comment by campagnola** [comment]
Tag is up; use `test-data-2`.
You will need to `git pull --tags` on your end to update your test data repo as well (I think .. maybe the tester will do this for you).

**Pull request merged**
